<?php
/* This file was generated by the metarefresh module at 2017-01-27T12:20:38Z
 Do not update it manually as it will get overwritten
*/

$metadata['https://shibboleth.uta.fi/idp/shibboleth'] = array (
  'expire' => 1485864901,
  'protocols' => 
  array (
    0 => 'urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'keys' => 
  array (
    0 => 
    array (
      'encryption' => true,
      'signing' => true,
      'type' => 'X509Certificate',
      'X509Certificate' => 'MIIEbzCCA1egAwIBAgIQWJ0Uu68P2AMpFdKpOgOPRDANBgkqhkiG9w0BAQUFADA2
MQswCQYDVQQGEwJOTDEPMA0GA1UEChMGVEVSRU5BMRYwFAYDVQQDEw1URVJFTkEg
U1NMIENBMB4XDTEzMTIxMTAwMDAwMFoXDTE3MDEwODIzNTk1OVowPzEhMB8GA1UE
CxMYRG9tYWluIENvbnRyb2wgVmFsaWRhdGVkMRowGAYDVQQDExFzaGliYm9sZXRo
LnV0YS5maTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKdw/yo3Lbk+
jpCHDDZ4M3At6zmkcEjMXmoyIEf/JtrdS7jictu5JbtdBq2tF1pghbwam0OoebBt
JOeMhA5kRT8L4A7q75SlOAgLOGn8pF+Nmzeh4GMdUM0bNMQU35yuVv2mqzoWk2bf
gfzHaUPyClu1YYus09CXCqDTKYzzWdSOLLm/Gwh2hcq93sdQnG2bnL5VB7Aranw5
Jxp7Lr1cGv8TLVh/UxusZAY230Tg2E9J2MiHtiXBC6zIVWMFqH46xVLpaEj5qq83
y0CDtUuTg9iNOnujnBW0p0c0ncHWo1J1NN3KQNep8qBRlXeDfpYd0tyQXElsLHwA
CFMRl0Qb0t0CAwEAAaOCAW4wggFqMB8GA1UdIwQYMBaAFAy9k2gM896ro0lrKzdX
R+qQ47ntMB0GA1UdDgQWBBQHZ33wMzTaJ63+SHUEjeM0I81mBzAOBgNVHQ8BAf8E
BAMCBaAwDAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
AwIwIgYDVR0gBBswGTANBgsrBgEEAbIxAQICHTAIBgZngQwBAgEwOgYDVR0fBDMw
MTAvoC2gK4YpaHR0cDovL2NybC50Y3MudGVyZW5hLm9yZy9URVJFTkFTU0xDQS5j
cmwwbQYIKwYBBQUHAQEEYTBfMDUGCCsGAQUFBzAChilodHRwOi8vY3J0LnRjcy50
ZXJlbmEub3JnL1RFUkVOQVNTTENBLmNydDAmBggrBgEFBQcwAYYaaHR0cDovL29j
c3AudGNzLnRlcmVuYS5vcmcwHAYDVR0RBBUwE4IRc2hpYmJvbGV0aC51dGEuZmkw
DQYJKoZIhvcNAQEFBQADggEBAImCKMUf2qlnocIu68mg7acEc+Wqbjmkg/Y0NEUr
esosCNMWkyWrvugRL2sXJ2JKOlzn3ivS5V7d2KbAOWIaX3WURTCoinUMjXoKu7av
1rHxYbexNPEcZZWlpzP9POTFQsKkMn8skqOADHTawOnTrQ8mAf9w93E0MuEzArCN
WZxb93Oky2XoDssu7YLnMurBAq5odfc+UEN4xAiKHOrIRYlswcQq9s6GVMO6GX5L
fK2v/tIcR6ODF7srxhs3AMZchoWljFoWBl+ZZwuyN7Sioh+5gRaFT9DhTaWw0WxM
JFOZQrlkdonIfIBEIk8JTF6Wg6Hp6dr33wBB7xapJqAhTjM=',
    ),
  ),
  'scope' => 
  array (
    0 => 'uta.fi',
  ),
  'tags' => 
  array (
    0 => 'kalmar',
  ),
  'EntityAttributes' => 
  array (
  ),
  'UIInfo' => 
  array (
  ),
  'DiscoHints' => 
  array (
  ),
  'entityid' => 'https://shibboleth.uta.fi/idp/shibboleth',
  'metadata-set' => 'attributeauthority-remote',
  'AttributeService' => 
  array (
    0 => 
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
      'Location' => 'https://shibboleth.uta.fi/idp/profile/SAML1/SOAP/AttributeQuery',
    ),
  ),
  'AssertionIDRequestService' => 
  array (
  ),
  'NameIDFormat' => 
  array (
    0 => 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient',
  ),
  'authproc' => 
  array (
    51 => 
    array (
      'class' => 'core:AttributeMap',
      0 => 'oid2name',
    ),
  ),
  'metarefresh:src' => 'https://kalmar2.org/simplesaml/module.php/aggregator/?id=kalmarcentral&set=saml2&exclude=norway',
);

$metadata['https://idp.metropolia.fi/idp'] = array (
  'expire' => 1485864901,
  'protocols' => 
  array (
    0 => 'urn:oasis:names:tc:SAML:1.1:protocol',
    1 => 'urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'keys' => 
  array (
    0 => 
    array (
      'encryption' => true,
      'signing' => true,
      'type' => 'X509Certificate',
      'X509Certificate' => 'MIIEbzCCA1egAwIBAgIQCc/9tdLS4HQLd5HGhihrEDANBgkqhkiG9w0BAQUFADA2
MQswCQYDVQQGEwJOTDEPMA0GA1UEChMGVEVSRU5BMRYwFAYDVQQDEw1URVJFTkEg
U1NMIENBMB4XDTE0MDQxMTAwMDAwMFoXDTE3MDQxMDIzNTk1OVowPzEhMB8GA1UE
CxMYRG9tYWluIENvbnRyb2wgVmFsaWRhdGVkMRowGAYDVQQDExFpZHAubWV0cm9w
b2xpYS5maTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMhuaEYcvTxQ
wONs2/tCwUNGN3cvP03SK+v4Gm+y3gezXXrISULJjY+sAz4qbuCtyQjewsLe3QL/
P+fgrF8iWwLxvFANqT0PU3NbiTfweYw4imGF71uB1+BTDeTkVisCbg3ki+owshif
aKFbO0ukOTUTx5vlBBkw1xFMAAMkttThMWZaAzTFDqnDuNhHnSP9botMOT7MDNJG
YZh0cXRpyHRRSYmjvcI59iPJwC/zQIoGWskwc3+UyhlFFSX1zF5cKOLQXo1i+VBc
bqf3/4VJiABIKPeyxsVvFIdo2pkylqUmm8E+wppKfPhnuK5dW8afApaqU/A4p8eh
9hWDMofDicMCAwEAAaOCAW4wggFqMB8GA1UdIwQYMBaAFAy9k2gM896ro0lrKzdX
R+qQ47ntMB0GA1UdDgQWBBTgVJX1n83Ge6l78jjijOdYXkXNhTAOBgNVHQ8BAf8E
BAMCBaAwDAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
AwIwIgYDVR0gBBswGTANBgsrBgEEAbIxAQICHTAIBgZngQwBAgEwOgYDVR0fBDMw
MTAvoC2gK4YpaHR0cDovL2NybC50Y3MudGVyZW5hLm9yZy9URVJFTkFTU0xDQS5j
cmwwbQYIKwYBBQUHAQEEYTBfMDUGCCsGAQUFBzAChilodHRwOi8vY3J0LnRjcy50
ZXJlbmEub3JnL1RFUkVOQVNTTENBLmNydDAmBggrBgEFBQcwAYYaaHR0cDovL29j
c3AudGNzLnRlcmVuYS5vcmcwHAYDVR0RBBUwE4IRaWRwLm1ldHJvcG9saWEuZmkw
DQYJKoZIhvcNAQEFBQADggEBAL7QxHjz3sE9LRXAFbxufA3DLDOvlzotP/x01Czh
7kVp5CdUsMFZU1lPQ9Kxc5kAa+doh9m4ZEamsBdLdGx3eFZEmzq41n86EImHZhGb
tWiMfx2qRTWga8WcYgAXW+6TzYP5CAxKxY4eBKKpvE9fsKxE5rKfByt+ZTQ51LgG
b8SiSXWGmD5k1VIVZ0Y0W2OTmOuAk52Sq4QwaAaJaHWRMvvmX7HxeIDLHpAqxDcc
qgNggMzs4qK6OjBIA6gCWwre1eRyeS2H1vC0rOhqqmLO5Y6vXw2odVYnKfD5pZHJ
G+Dx7F2feFhAdfZyEz66oAuniAeUWSFMijlxsqfDKgfg5YY=',
    ),
  ),
  'scope' => 
  array (
    0 => 'metropolia.fi',
  ),
  'tags' => 
  array (
    0 => 'kalmar',
  ),
  'EntityAttributes' => 
  array (
  ),
  'UIInfo' => 
  array (
  ),
  'DiscoHints' => 
  array (
  ),
  'entityid' => 'https://idp.metropolia.fi/idp',
  'metadata-set' => 'attributeauthority-remote',
  'AttributeService' => 
  array (
    0 => 
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:1.0:bindings:SOAP-binding',
      'Location' => 'https://idp.metropolia.fi/idp/profile/SAML1/SOAP/AttributeQuery',
    ),
    1 => 
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:SOAP',
      'Location' => 'https://idp.metropolia.fi/idp/profile/SAML2/SOAP/AttributeQuery',
    ),
  ),
  'AssertionIDRequestService' => 
  array (
  ),
  'NameIDFormat' => 
  array (
    0 => 'urn:mace:shibboleth:1.0:nameIdentifier',
    1 => 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient',
  ),
  'authproc' => 
  array (
    51 => 
    array (
      'class' => 'core:AttributeMap',
      0 => 'oid2name',
    ),
  ),
  'metarefresh:src' => 'https://kalmar2.org/simplesaml/module.php/aggregator/?id=kalmarcentral&set=saml2&exclude=norway',
);

$metadata['https://idp.nordu.net/idp/shibboleth'] = array (
  'expire' => 1485548226,
  'protocols' => 
  array (
    0 => 'urn:oasis:names:tc:SAML:1.1:protocol',
    1 => 'urn:oasis:names:tc:SAML:2.0:protocol',
  ),
  'keys' => 
  array (
    0 => 
    array (
      'encryption' => true,
      'signing' => true,
      'type' => 'X509Certificate',
      'X509Certificate' => '
MIIDHzCCAgegAwIBAgIUbYzFMX2BKRKmZwRSWg0HZ3/MQQwwDQYJKoZIhvcNAQEF
BQAwGDEWMBQGA1UEAxMNaWRwLm5vcmR1Lm5ldDAeFw0wOTA5MDMxOTI4NDlaFw0y
OTA5MDMxOTI4NDlaMBgxFjAUBgNVBAMTDWlkcC5ub3JkdS5uZXQwggEiMA0GCSqG
SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCSypIpdblxznunPXiwKCqwOYmj99u5S9f7
RTR+s8EDs01uwJ8buJs0MId+s96mD8MIkobE4iwn/B6xlafbMr3/BF+XxxH8Q5WX
Bf3aQV3ohBqur6+mRQ2C+EenzPMGHmV/FCz0cbmTsIAQHZ9Vy16H+x5uWOBVd44i
CMLM+fgjKyYcpcEUJP9Jkn/+d36L3mdXbyqAQS2UPN+S1g37xrgR2kWW+s1lMEiR
M/f5L+PuA3l5DxIBmK0tFo+ZPLxbr6OBWOdH6EUbfdkvfciFCVNbWBGRW5MC2aru
ATCdtf/Vev3OngUYBGSR/94eTgMcs3Oww/ppxRS6dzntGnnCT1sPAgMBAAGjYTBf
MD4GA1UdEQQ3MDWCDWlkcC5ub3JkdS5uZXSGJGh0dHBzOi8vaWRwLm5vcmR1Lm5l
dC9pZHAvc2hpYmJvbGV0aDAdBgNVHQ4EFgQUwPXuksUpm5OdopeWHdoRcs6wCu0w
DQYJKoZIhvcNAQEFBQADggEBAHiPOKmhiLnx8ecuQHmwmh4DUZvarhZXNtgxyasU
bZAfPoZn8YiELiqYQoA/j+hoAfWcCEafMgjm8nkQO9aad1cwpGY66SIRKPAKBgsW
nOugnrREWwYl1tXG3VWYzpgygycziYzkmwc4ysHQATKjCYdulA1tZ09YiAnZOIzY
Q93/gA7X177nVKnAbmSkY1Nap4/rbkHIvQqk8RPSYs5AwasThkEFVk4OQpPtoTOn
aOBLkJxpXY7rZDixrz59ny629qmOOakSCsuVkNwDPmbLQy9dKmHXTcge2xP0mDK7
JiNCTXH29oP8kWBEBVaDxrDIrfDv53VjURS+KXqpBLjsuVE=

                    ',
    ),
  ),
  'scope' => 
  array (
    0 => 'nordu.net',
  ),
  'tags' => 
  array (
    0 => 'kalmar',
  ),
  'EntityAttributes' => 
  array (
  ),
  'UIInfo' => 
  array (
  ),
  'DiscoHints' => 
  array (
  ),
  'entityid' => 'https://idp.nordu.net/idp/shibboleth',
  'metadata-set' => 'attributeauthority-remote',
  'AttributeService' => 
  array (
    0 => 
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:1.0:bindings:SOAP-binding',
      'Location' => 'https://idp.nordu.net:8443/idp/profile/SAML1/SOAP/AttributeQuery',
    ),
    1 => 
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:SOAP',
      'Location' => 'https://idp.nordu.net:8443/idp/profile/SAML2/SOAP/AttributeQuery',
    ),
  ),
  'AssertionIDRequestService' => 
  array (
  ),
  'NameIDFormat' => 
  array (
    0 => 'urn:mace:shibboleth:1.0:nameIdentifier',
    1 => 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient',
  ),
  'authproc' => 
  array (
    51 => 
    array (
      'class' => 'core:AttributeMap',
      0 => 'oid2name',
    ),
  ),
  'metarefresh:src' => 'https://kalmar2.org/simplesaml/module.php/aggregator/?id=kalmarcentral&set=saml2&exclude=norway',
);

?>